version: '3.8'

services:
  # FHEVM Local Node (for development)
  fhevm-node:
    image: zama-ai/fhevm-node:latest
    container_name: fhevm-local-node
    ports:
      - "8545:8545"
      - "8546:8546"
    environment:
      - NETWORK_ID=31337
      - CHAIN_ID=31337
    volumes:
      - fhevm_data:/data
    networks:
      - fhevm-network
    restart: unless-stopped

  # FHEVM Relayer (for encryption/decryption)
  fhevm-relayer:
    image: zama-ai/fhevm-relayer:latest
    container_name: fhevm-relayer
    ports:
      - "8080:8080"
    environment:
      - NODE_URL=http://fhevm-node:8545
      - PORT=8080
    depends_on:
      - fhevm-node
    networks:
      - fhevm-network
    restart: unless-stopped

  # FHEScore Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fhescore-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_CONTRACT_ADDRESS=${REACT_APP_CONTRACT_ADDRESS}
      - REACT_APP_NETWORK_ID=31337
      - REACT_APP_NETWORK_NAME=localhost
      - REACT_APP_FHEVM_RELAYER_URL=http://localhost:8080
    depends_on:
      - fhevm-relayer
    networks:
      - fhevm-network
    restart: unless-stopped

volumes:
  fhevm_data:

networks:
  fhevm-network:
    driver: bridge